//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class DoorLockLog
{
	private bool _disabled { get; set; }
	private string _lockState { get; set; }
	private object _timeStamp { get; set; }
	private int _codeAttempt { get; set; }
	private string _logFilePath { get; set; }	

	internal virtual void LogState(string codeAttempt, bool isLocked, bool isDisabled)
	{
		throw new System.NotImplementedException();
	}
	public virtual void ToString()
	{
		throw new System.NotImplementedException();
	}

}

