//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows;

public class DoorLockGui  
{
	private DoorLock Lock;

	private object Timer
	{
		get;
		set;
	}

	private string _attempt
	{
		get;
		set;
	}

	private void btnNumber_Click()
	{
		throw new System.NotImplementedException();
	}

	private void btnClear_Click()
	{
		throw new System.NotImplementedException();
	}

	private void btnEnter_Click()
	{
		throw new System.NotImplementedException();
	}

	private void DisabledKeypad()
	{
		throw new System.NotImplementedException();
	}

	private void LockoutTimer_Tick()
	{
		throw new System.NotImplementedException();
	}

	private void EnableKeypad()
	{
		throw new System.NotImplementedException();
	}

	private void HotKeyPress()
	{
        throw new System.NotImplementedException();
    }

	public virtual void DoorLockKeypad()
	{
		throw new System.NotImplementedException();
	}

}

